tap "av1155/scripts", "https://github.com/av1155/scripts.git"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "jstkdng/programs"
tap "samtay/tui"
tap "supabase/tap"
# Extremely Fast Compression algorithm
brew "lz4"
# Zstandard is a real-time compression algorithm
brew "zstd"
# Image format providing lossless and lossy compression for web images
brew "webp"
# Highly capable, feature-rich programming language
brew "perl"
# Aquarium animation in ASCII art
brew "asciiquarium"
# ChatGPT in the terminal
brew "ata"
# Automatic configure script builder
brew "autoconf"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Secure and free password manager for all of your devices
brew "bitwarden-cli"
# Yet another cross-platform graphical process/system monitor
brew "bottom"
# Hacker News in your terminal
brew "circumflex"
# Cross-platform make
brew "cmake"
# Console Matrix
brew "cmatrix"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Dependency manager for Cocoa projects
brew "cocoapods"
# Pure Scala Artifact Fetching
brew "coursier"
# Get, unpack, build, and install modules from CPAN
brew "cpanminus"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Load/unload environment variables based on $PWD
brew "direnv"
# Modern, maintained replacement for ls
brew "eza"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Low-level access to audio, keyboard, mouse, joystick, and graphics
brew "sdl2"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# Disk usage analyzer with console interface written in Go
brew "gdu"
# WebDriver <-> Marionette proxy
brew "geckodriver"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Quickly rewrite git repository history
brew "git-filter-repo"
# Render markdown on the CLI
brew "glow"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle"
# Kubernetes package manager
brew "helm"
# Generic library support script
brew "libtool"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Fast, Dynamic Programming Language
brew "julia"
# Library for USB device access
brew "libusb"
# Parsing Expression Grammars For Lua
brew "lpeg"
# Package manager for the Lua programming language
brew "luarocks"
# Text-based web browser
brew "lynx"
# Mac App Store command-line interface
brew "mas"
# Java-based project management
brew "maven"
# Remote terminal application
brew "mosh"
# SMTP client that can be used as an SMTP plugin for Mutt
brew "msmtp"
# Netwide Assembler (NASM) is an 80x86 assembler
brew "nasm"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Package for scientific computing with Python
brew "numpy"
# Web-based PostgreSQL database browser
brew "pgweb"
# Parallel gzip
brew "pigz"
# Python dependency management tool
brew "pipenv"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Paste PNG into files
brew "pngpaste"
# Theme for zsh
brew "powerlevel10k"
# Bundle a Python application and all its dependencies
brew "pyinstaller"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Generic machine emulator and virtualizer
brew "qemu"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Tools for Multiple Arcade Machine Emulator
brew "rom-tools"
# Safe, concurrent, practical language
brew "rust"
# Rust toolchain installer
brew "rustup"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Cross-shell prompt for astronauts
brew "starship"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Open source continuous file synchronization application
brew "syncthing", restart_service: :changed
# User interface to the TELNET protocol
brew "telnet"
# Programmatically correct mistyped console commands
brew "thefuck"
# Official tldr client written in Rust
brew "tlrc"
# Terminal multiplexer
brew "tmux"
# Command-line interface for Vercel
brew "vercel-cli"
# Vi 'workalike' with many additional features
brew "vim"
# Simple terminal image viewer written in Rust
brew "viu"
# Internet file retriever
brew "wget"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Easily compile and run Java files, manage cleanup, and view syntax-highlighted errors through a user-friendly fuzzy-finding menu.
brew "av1155/scripts/javaprojectmanager"
# Everything you need to get started with Heroku
brew "heroku/brew/heroku"
# A simple terminal UI for git commands, written in Go
brew "jesseduffield/lazygit/lazygit"
# Tetris in your terminal
brew "samtay/tui/tetris"
# Supabase CLI
brew "supabase/tap/supabase"
# View, create, manipulate, print and manage files in Portable Document Format
cask "adobe-acrobat-pro"
# Collection of apps and services for photography, design, video, web, and UX
cask "adobe-creative-cloud"
# Menu bar tool to limit maximum charging percentage
cask "aldente"
# Enable Windows-like alt-tab
cask "alt-tab"
# Memory training application
cask "anki"
# Application uninstaller
cask "appcleaner"
# Chromium based browser
cask "arc"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Desktop app for GPT-4 / GPT-3.5 (OpenAI API)
cask "chatbox"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# Hardware benchmarking utility
cask "cinebench"
# UI for creating Windows installer ISO from UUPDump
cask "crystalfetch"
# Browser for SQLite databases
cask "db-browser-for-sqlite"
# Voice and text chat software
cask "discord"
# Developer platform
cask "dotnet-sdk"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
# UI toolkit for building applications for mobile, web and desktop
cask "flutter"
# Clipboard manager for developers
cask "flycut"
# Tool to measure the computer system's performance
cask "geekbench"
# Web browser
cask "google-chrome"
# Tool to optimise images to a smaller size
cask "imageoptim"
# JetBrains tools manager
cask "jetbrains-toolbox"
# Open-source keystroke visualiser
cask "keycastr"
# GPU-based terminal emulator
cask "kitty"
# Discover, download, and run local LLMs
cask "lm-studio"
# Full TeX Live distribution with GUI applications
cask "mactex"
# Scanner app for math and science
cask "mathpix-snipping-tool"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Multi-platform web browser
cask "microsoft-edge"
# Office suite
cask "microsoft-office"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Minimal installer for conda specific to conda-forge
cask "miniforge"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Game launcher with the ability to run Windows games
cask "mythic"
# App to write, plan, collaborate, and get organised
cask "notion"
# Get up and running with large language models locally
cask "ollama"
# Verify system files structure, run miscellaneous maintenance and more
cask "onyx"
# Client program for the OpenVPN Access Server
cask "openvpn-connect"
# Quick Look generator for Markdown files
cask "qlmarkdown"
# Environment for statistical computing and graphics
cask "r"
# Imaging utility to install operating systems to a microSD card
cask "raspberry-pi-imager"
# Control your tools with a few keystrokes
cask "raycast"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# MySQL/MariaDB database management
cask "sequel-ace"
# Screenshot measurement and annotation tool
cask "shottr"
# Team communication and collaboration software
cask "slack"
# Application to control your PlayStation 4 or PlayStation 5
cask "sony-ps-remote-play"
# Music streaming service
cask "spotify"
# System monitor for the menu bar
cask "stats"
# Video game digital distribution service
cask "steam"
# SSH client
cask "termius"
# Unpacks archive files
cask "the-unarchiver"
# To-do & task list manager
cask "ticktick"
# AI image upscaler
cask "upscayl"
# Virtual machines UI using QEMU
cask "utm"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Remote desktop application focusing on security
cask "vnc-viewer"
# Native desktop client for WhatsApp
cask "whatsapp"
# Wine wrapper built with SwiftUI
cask "whisky"
# Video communication and virtual meeting platform
cask "zoom"
vscode "adpyke.codesnap"
vscode "alefragnani.project-manager"
vscode "batisteo.vscode-django"
vscode "be5invis.vscode-custom-css"
vscode "bradlc.vscode-tailwindcss"
vscode "catppuccin.catppuccin-vsc"
vscode "chakrounanas.turbo-console-log"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "denoland.vscode-deno"
vscode "donjayamanne.python-environment-manager"
vscode "donjayamanne.python-extension-pack"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "github.codespaces"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "golang.go"
vscode "kevinrose.vsc-python-indent"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "liviuschera.noctis"
vscode "mechatroner.rainbow-csv"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.autopep8"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "njpwerner.autodocstring"
vscode "openai.openai-chatgpt-adhoc"
vscode "pdconsec.vscode-print"
vscode "pflannery.vscode-versionlens"
vscode "pkief.material-icon-theme"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "richie5um2.vscode-sort-json"
vscode "ritwickdey.liveserver"
vscode "silesky.toggle-boolean"
vscode "tomoki1207.pdf"
vscode "twxs.cmake"
vscode "usernamehw.errorlens"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "wallabyjs.console-ninja"
vscode "wayou.vscode-todo-highlight"
vscode "wholroyd.jinja"
vscode "xaver.clang-format"
